### ISSUE TITLE
Petition- Tally Ho has to be set as default wallet in order to sign

### ISSUE THREAD

**Issue by chlolands** [tallycash/tally.cash#86] opened 2022-08-22 19:50 UTC
In QAing with my MM wallet, it disabled Tally Ho as the default, when I went to sign, it prompted me to download for Chrome/Brave.

**Comment by 0xDaedalus** [comment] 2022-08-22 19:59
Duplicate of #82

**Closed by 0xDaedalus** 2022-08-22 19:59 UTC
